Minor fix keyword argument
This was causing problems when loading the package to the cluster. It gives the following error

LoadError: LoadError: syntax: invalid keyword argument syntax